apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordenappweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordenappweb
  template:
    metadata:
      labels:
        app: ordenappweb
    spec:
      containers:
      - name: ordenappweb
        image: nicolasmd/ordenappweb:latest
        ports:
        - containerPort: 3000