version: '3'
services:
#  db:
#    image: postgres
#    environment:
#      POSTGRES_PASSWORD: password
#      POSTGRES_USER: user
#      POSTGRES_DB: myapp_development
  web:
    image: nicolasmd/ordenappweb:latest
    ports:
      - "3000:3000"
#    depends_on:
#      - db
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://nicolasmd:4dm1nOrdenapp@database-1.c3oyceysazyw.us-east-1.rds.amazonaws.com:5432