version: '3'
services:
  redis:
    image: redis:6.2
    networks:
      - app_network
  
  web:
    build: .
    image: nicolasmd/ordenappweb:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - redis
#      - db
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      # RDS_HOST: 172.17.194.53
      # DATABASE_URL: postgres://nicolasmd:4dm1nOrdenapp@database-1.c3oyceysazyw.us-east-1.rds.amazonaws.com:5432
      # DATABASE_URL: postgres://nicolasmd:4dm1nOrdenapp@host.docker.internal:5432
    networks:
      - app_network

networks:
  app_network: