name: Deploy to AWS EC2

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/ordenappweb:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ordenappweb:latest
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}
      
      - name: Create .env file
        run: |
          echo "RDS_HOST=${{ secrets.RDS_HOST }}" >> .env.production
          echo "RDS_USERNAME=${{ secrets.RDS_USERNAME }}" >> .env.production
          echo "RDS_PASSWORD=${{ secrets.RDS_PASSWORD }}" >> .env.production
          echo "RDS_PORT=${{ secrets.RDS_PORT }}" >> .env.production
          echo "aws_access_key_id=${{ secrets.aws_access_key_id }}" >> .env.production
          echo "aws_secret_access_key=${{ secrets.aws_secret_access_key }}" >> .env.production
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> .env.production
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env.production
          echo "GOOGLE_MAPS_API_SERVER_KEY=${{ secrets.GOOGLE_MAPS_API_SERVER_KEY }}" >> .env.production
          echo "SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}" >> .env.production
          echo "SENDGRID_PASSWORD=${{ secrets.SENDGRID_PASSWORD }}" >> .env.production
          echo "SENDGRID_USERNAME=${{ secrets.SENDGRID_USERNAME }}" >> .env.production
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env.production
          scp -o StrictHostKeyChecking=no .env.production ubuntu@${{ secrets.AWS_EC2_HOST }}:/home/ubuntu/deploy

      - name: Ensure deploy directory exists on EC2
        run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_HOST }} 'mkdir -p /home/ubuntu/deploy && chmod 755 /home/ubuntu/deploy'
      
      - name: Copy deploy script to EC2
        run: scp -o StrictHostKeyChecking=no deploy_script.sh ubuntu@${{ secrets.AWS_EC2_HOST }}:/home/ubuntu/deploy

      - name: Copy docker-compose.yml to EC2
        run: scp -o StrictHostKeyChecking=no docker-compose.yml ubuntu@${{ secrets.AWS_EC2_HOST }}:/home/ubuntu/deploy

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_HOST }} 'bash /home/ubuntu/deploy_script.sh'
